import Head from "next/head";
import Image from "next/image";
import { Formik } from "formik";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1 className="text-3xl font-bold">ELI5!</h1>
				<h1 className="text-xl">Explain Like I&#39;m Five</h1>
				<p className="text-m font-light">Inspired by Vipin</p>
				<Formik
					initialValues={{ text: "" }}
					validate={(values) => {
						const errors = {};
						if (!values.text) {
							errors.text = "Required";
						}
						return errors;
					}}
					onSubmit={(values, { setSubmitting }) => {
						setTimeout(() => {
							alert(JSON.stringify(values, null, 2));
							const res = await fetch(`/api/openai`, {
								body: JSON.stringify({
									name: search,
								}),
								headers: {
									"Content-Type": "application/json",
								},
								method: "POST",
							});
							setSubmitting(false);
						}, 400);
					}}
				>
					{({
						values,
						errors,
						touched,
						handleChange,
						handleBlur,
						handleSubmit,
						isSubmitting,
						/* and other goodies */
					}) => (
						<form onSubmit={handleSubmit}>
							<input
								type="text"
								name="text"
								onChange={handleChange}
								onBlur={handleBlur}
								value={values.email}
							/>
							{errors.text && touched.text && errors.text}
							<button
								type="submit"
								className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
								disabled={isSubmitting}
							>
								Submit
							</button>
						</form>
					)}
				</Formik>
			</main>
		</div>
	);
}
