import Head from "next/head";
import { Formik, Field, Form } from "formik";

export default function Home() {
	return (
		<div>
			<Head>
				<title>OpenAI GPT-3 tester</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<h1 className="text-3xl font-bold">OpenAI GPT-3 tester</h1>
				<h1 className="text-xl">Simple, private, no logging</h1>
				<Formik
					initialValues={{
						enteredText: "",
					}}
					// Below section entire written/prompted by GitHub CodePilot
					onSubmit={async (values) => {
						const response = await fetch("/api/openai", {
							method: "POST",
							headers: {
								"Content-Type": "application/json",
							},
							body: JSON.stringify({
								name: enteredText,
							}),
						});
						const data = await response.json();
						console.log(data);
					}}
				>
					{({ isSubmitting }) => (
						<Form>
							<Field
								type="textarea"
								as="textarea"
								className="mt-5 mb-5 w-1/2 block rounded-md bg-gray-100	border-transparent focus:border-gray-500 focus:bg-white focus:ring-0"
								name="enteredText"
								placeholder="Enter your text here"
							/>
							<button
								className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
								type="submit"
								disabled={isSubmitting}
							>
								Submit
							</button>
						</Form>
					)}
				</Formik>
			</main>
			<footer>
				<p className="text-sm font-light">Thanks to Vipin for the idea</p>
				<p className="text-m font-light">
					Built with Next.js, OpenAI (GPT-3) API
				</p>
			</footer>
		</div>
	);
}
